#!/bin/bash

# xrandr --output eDP1 --mode 1600x900 --rate 59.82

# setxkbmap -variant colemak

polybar main &

xfce-power-manager &

ibus-daemon -d -x &
nitrogen --restore &
lxsession &

dunst &
picom &
