#!/bin/sh

sxhkd &
sh ~/.config/bspwm/autostart &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width	2
bspc config window_gap		80

bspc config top_padding             60
bspc config split_ratio             0.52
bspc config borderless_monocle      false
bspc config gapless_monocle         false

bspc config focused_border_color	"#59CCF2"
bspc config urgent_border_color		"#FFD300"

bspc config click_to_focus	true
bspc config pointer_action1	move
bspc config pointer_action2	resize_side
bspc config pointer_action3	resize_corner

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a mplayer2 state=floating
bspc rule -a Pamac-manager state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a Font-manager state=floating
