#!/bin/sh

sxhkd &
sh ~/.config/bspwm/autostart &

bspc monitor -d web code media terminal chat desktop

bspc config border_width    1
bspc config window_gap      0

bspc config top_padding             0
bspc config left_padding            0
bspc config bottom_padding          28
bspc config right_padding           0
bspc config split_ratio             0
bspc config borderless_monocle      false
bspc config gapless_monocle         false

bspc config focused_border_color    "#59CCF2"
bspc config urgent_border_color	    "#FFD300"

bspc config click_to_focus  true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a mplayer2 state=floating
bspc rule -a Pamac-manager state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a Font-manager state=floating
