#! /bin/sh

sxhkd &
sh ~/.config/bspwm/autostart.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	3
bspc config window_gap		20

bspc config split_ratio		0.5

bspc config normal_border_color		"#F3FBFE"
bspc config focused_border_color	"#59CCF2"
bspc config urgent_border_color		"#FFD300"

bspc config click_to_focus	true
bspc config pointer_action1	move
bspc config pointer_action2	resize_side
bspc config pointer_action3	resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Pamac-manager state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a Code state=floating
bspc rule -a Font-manager state=floating
