#!/bin/bash

cd `dirname $0`

source ./.config/helpers/dotfiles


initialize


target_dir="$HOME"

files=(
    .xinitrc
    .xsession
    .bashrc

    .Xresources
    .Xresources.d

    .config/helpers

    .config/bspwm
    .config/sxhkd
    .config/rofi
    .config/dunst
    .config/polybar

    .config/scripts

    .config/libinput-gestures.conf
)

run


teardown
